### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Pooort** [mhelwig/apk-anal#7]
```
[*] Opening dexfile with radare2...
Traceback (most recent call last):
  File "apk-anal/apk-anal.py", line 305, in <module>
    print_results(rootresults,{"found":"\n[*] Possible root detection found in %s:","not_found":"\n[*] No signs of root detection in %s"},r2p)
  File "apk-anal/apk-anal.py", line 173, in print_results
    for key,result in analysis_results.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by juergenhoetzel** [comment]
Should be fixed by #8
